let paises = [
  {
    nombre: "Colombia",
    saludo: "Hola bienvenido ",
    idioma: "Español",
    gentilicio: "Colombiano",
    moneda: "Peso Colombiano",
    capital: "Bogotá",
    color: "#FFC300",
  },
  {
    nombre: "Alemania",
    saludo: "Hallo, Willkommen ",
    idioma: "Aleman",
    gentilicio: "Germano",
    moneda: "Euro",
    capital: "Berlin",
    color: "#000",
  },
  {
    nombre: "Brasil",
    saludo: "Olá bem vindo ",
    idioma: "Portugués",
    gentilicio: "Brasileño",
    moneda: "Real Brasileño",
    capital: "Brasilia",
    color: "#138d75",
  },
  {
    nombre: "Canadá",
    saludo: "Hello welcome ",
    idioma: "Ingles",
    gentilicio: "Canadiense",
    moneda: "Dolar canadiense",
    capital: "Ottawa",
    color: "#e74c3c",
  },
  {
    nombre: "Francia",
    saludo: "Bonjour bienvenue ",
    idioma: "Francés",
    gentilicio: "Francés",
    moneda: "Euro",
    capital: "Paris",
    color: "#3498db",
  },
  {
    nombre: "Italia",
    saludo: "Ciao benvenuto ",
    idioma: "Italiano",
    gentilicio: "Italiano",
    moneda: "Euro",
    capital: "Roma",
    color: "#ecf0f1",
  },
  {
    nombre: "Japón",
    saludo: "こんにちはようこそ ",
    idioma: "Japones",
    gentilicio: "Japones",
    moneda: "Yen",
    capital: "Tokio",
    color: "#a93226",
  },
  {
    nombre: "Rumania",
    saludo: "buna bine ai venit ",
    idioma: "Rumano",
    gentilicio: "Rumano",
    moneda: "Leu rumano",
    capital: "Bucarest",
    color: "#b9770e ",
  }
];
